kinesis:
  image: pzielinski4/kinesis:latest
  volumes:
       - type: bind
         source: ${HOST_LOCATION}
         target: ${CONTAINER_LOCATION}
  command: python3 ${CONTAINER_LOCATION}/video_to_json.py
