kinesis:
  image: pzielinski4/kinesis:latest
  volumes:
       - type: bind
         source: ${HOSTLOCATION}
         target: ${CONTAINERLOCATION}
  command: python3 ${CONTAINERLOCATION}/video_to_json.py
