kinesis:
  image: pzielinski4/kinesis:latest
  command: gst-launch-1.0 rtspsrc location="${RSTP_LOCATION}" short-header=TRUE ! rtph264depay ! h264parse ! kvssink stream-name="${AWS_STREAM_NAME}" storage-size=512 access-key="${AWS_ACCESS_KEY}" secret-key="${AWS_SECRET_KEY}" aws-region="${AWS_REGION}"
  command: gst-launch-1.0 -e rtspsrc location="${RSTP_LOCATION}" ! short-header=TRUE ! rtph264depay ! video/x-h264, format=avc,alignment=au ! filesink location=~/Camera1.mp4
